name: CI

on: [push, pull_request]

jobs:
  console-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100

      - name: Build & test
        run: dotnet test
        env:
          DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
          
  redirected-output:
    runs-on: ubuntu latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.100
    
      - name: Build & test (redirected)
        run: dotnet test > out.txt
        env:
          DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
          
      - name: Upload output
        uses: actions/upload-artifact@v3.0.0
        with:
          path: out.txt
